version: "3.2"
services:
  traefik:
    image: traefik:latest
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc:/etc/traefik:ro
      - ./acme.json:/opt/cert/acme.json:rw

  whoami:
    image: containous/whoami:latest
    labels: 
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)
      - traefik.http.routers.whoami.service=whoami@docker
      - traefik.http.routers.whoami.tls.certresolver=lets-encr
      - traefik.http.services.whoami.loadbalancer.server.port=80

  nginx:
    image: nginx:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.rule=Host(`nginx.localhost`)
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.service=nginx@docker
      - traefik.http.services.nginx.loadbalancer.server.port=80
