global:
  checkNewVersion: false
  sendAnonymousUsage: false
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          priority: 10
  websecure:
    address: :443
log:
  level: DEBUG
#  filePath: /var/log/traefik/traefik.log
#  format: json
accessLog:
#  filePath: /var/log/traefik/access.log
  format: json
api:
  insecure: true
#  dashboard: false
providers:
  swarm:
    endpoint: unix:///var/run/docker.sock
    network: traefik_external
    exposedByDefault: false
