global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          priority: 10
  websecure:
    address: :443
    http3:
      advertisedPort: 443

log:
  level: INFO
  format: json
  filePath: /var/log/traefik/traefik.log

accessLog:
  format: json
  filePath: /var/log/traefik/access.log

api:
  insecure: true
#  dashboard: false

providers:
  swarm:
    endpoint: unix:///var/run/docker.sock
    network: traefik_external
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
