global:
  checkNewVersion: false
  sendAnonymousUsage: false
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          priority: 10
  websecure:
    address: :443
log:
  level: INFO
#  filePath: /var/log/traefik/traefik.log
#  format: json
accessLog:
#  filePath: /var/log/traefik/access.log
  format: common
api:
  insecure: true
#  dashboard: false
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    swarmMode: true
    network: traefik_external
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true